import { Item } from "../types";

export const initialItems: Item[] = [
    {
        id: 1,
        ingredientId: 1,
        price: 200,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 3 * 24 * 60 * 60 * 1000),
    },
    {
        id: 2,
        ingredientId: 2,
        price: 100,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    },
    {
        id: 3,
        ingredientId: 3,
        price: 150,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 2 * 24 * 60 * 60 * 1000),
    },
    {
        id: 4,
        ingredientId: 4,
        price: 250,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 4 * 24 * 60 * 60 * 1000),
    },
    {
        id: 5,
        ingredientId: 5,
        price: 130,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 4 * 24 * 60 * 60 * 1000),
    },
    {
        id: 6,
        ingredientId: 6,
        price: 160,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 5 * 24 * 60 * 60 * 1000),
    },
    {
        id: 7,
        ingredientId: 7,
        price: 300,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    },
    {
        id: 11,
        ingredientId: 11,
        price: 80,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 2 * 24 * 60 * 60 * 1000),
    },
    {
        id: 12,
        ingredientId: 12,
        price: 80,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 3 * 24 * 60 * 60 * 1000),
    },
    {
        id: 13,
        ingredientId: 13,
        price: 80,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 2 * 24 * 60 * 60 * 1000),
    },
    {
        id: 14,
        ingredientId: 14,
        price: 80,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 6 * 24 * 60 * 60 * 1000),
    },
    {
        id: 21,
        ingredientId: 21,
        price: 50,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 10 * 24 * 60 * 60 * 1000),
    },
    {
        id: 22,
        ingredientId: 22,
        price: 50,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 3 * 24 * 60 * 60 * 1000),
    },
    {
        id: 23,
        ingredientId: 23,
        price: 50,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    },
    {
        id: 24,
        ingredientId: 24,
        price: 50,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 2 * 24 * 60 * 60 * 1000),
    },
    {
        id: 31,
        ingredientId: 31,
        price: 100,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 5 * 24 * 60 * 60 * 1000),
    },
    {
        id: 32,
        ingredientId: 32,
        price: 100,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 6 * 24 * 60 * 60 * 1000),
    },
    {
        id: 33,
        ingredientId: 33,
        price: 100,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000),
    },
    {
        id: 41,
        ingredientId: 41,
        price: 140,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 2 * 24 * 60 * 60 * 1000),
    },
    {
        id: 42,
        ingredientId: 42,
        price: 140,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 4 * 24 * 60 * 60 * 1000),
    },
    {
        id: 43,
        ingredientId: 43,
        price: 140,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000),
    },
    {
        id: 44,
        ingredientId: 44,
        price: 140,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 6 * 24 * 60 * 60 * 1000),
    },
    {
        id: 51,
        ingredientId: 51,
        price: 170,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 6 * 24 * 60 * 60 * 1000),
    },
    {
        id: 52,
        ingredientId: 52,
        price: 170,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 4 * 24 * 60 * 60 * 1000),
    },
    {
        id: 53,
        ingredientId: 53,
        price: 170,
        currentAmount: Math.floor(Math.random() * 55),
        goal: Math.floor(Math.random() * 99) + 1,
        deadline: new Date(new Date().getTime() + 3 * 24 * 60 * 60 * 1000),
    },
];
